[package]
name = "tokio-process-pty"
version = "0.1.0"
authors = ["Miquel van Smoorenburg <mikevs@xs4all.net>"]
edition = "2018"

[dependencies]
mio = "0.6.20"
tokio = { version = "0.2.9", features = [ "full" ] }
lazy_static = "1.4.0"
libc = "0.2.66"
futures = "0.3.1"
nix = "0.16.1"

